version: 0.2
phases:
  pre_build:
    commands:
      - export CI_BRANCH_NAME="production"
      - echo "==> CI_BRANCH_NAME = $CI_BRANCH_NAME"
      - echo Logging into Amazon ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPO_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo "GIT COMMIT HASH  $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - IMAGE_TAG=${COMMIT_HASH}
  build:
    commands:
      - echo Maven Build
      - mvn clean package
artifacts:
  files:
    - maven-web-app.jar
